# app
app:
  pageSize: 10
  jwtSecret: 233
  prefixUrl: http://127.0.0.1:8080
  runtimeRootPath: runtime/
  imageSavePath: upload/images/
  # MB
  imageMaxSize: 5
  imageAllowExts: 
    - .jpg
    - .jpeg
    - .png
  exportSavePath: export/
  qrCodeSavePath: qrcode/
  fontSavePath: fonts/
  logSavePath: logs/
  logSaveName: log
  logFileExt: log
  timeFormat: 20060102

# server
server:
  runMode: debug
  httpPort: 8080
  readTimeout: 60s
  writeTimeout: 60s

database:
  type: mysql
  user: root
  password: root
  host: 127.0.0.1:3306
  name: ginapi
  tablePrefix: gin_

mongo:
  user: root
  password: root
  host: mongodb://localhost:27017
  name: gin_test

redis:
  password: 
  host: 127.0.0.1:6379
  maxIdle: 30
  maxActive: 30
  idleTimeout: 200s

session:
  #是否开启session
  sessionOn : true
  #设置session名称
  sessionName : sessionid
  sessionProvider : redis
  #配置 地址:端口,连接池,密码,库名
  host : 127.0.0.1:6379
  #cookie的有效期（秒），默认是session,即会话结束则过期
  sessionCookieLifetime : 86400
  #设置 Session 过期的时间，默认值是 3600 秒
  sessionGcmaxLifetime : 86400
  #空闲连接数
  maxIdleConns : 30
  #最大连接数
  poolSize : 200
  #库名
  db : 0

log:
  #错误路劲层级
  skip : 2

rediskey:
  #AuthUserKey
  authUserKey : AuthUserInfo